export interface Language {
  id: string;
  name: string;
}

export interface Theme {
  id: string;
  name: string;
  type: 'dark' | 'light';
}

export const POPULAR_LANGUAGES: Language[] = [
  { id: 'javascript', name: 'JavaScript' },
  { id: 'typescript', name: 'TypeScript' },
  { id: 'python', name: 'Python' },
  { id: 'java', name: 'Java' },
  { id: 'csharp', name: 'C#' },
  { id: 'cpp', name: 'C++' },
  { id: 'c', name: 'C' },
  { id: 'go', name: 'Go' },
  { id: 'rust', name: 'Rust' },
  { id: 'swift', name: 'Swift' },
  { id: 'kotlin', name: 'Kotlin' },
  { id: 'php', name: 'PHP' },
  { id: 'ruby', name: 'Ruby' },
  { id: 'html', name: 'HTML' },
  { id: 'css', name: 'CSS' },
  { id: 'scss', name: 'SCSS' },
  { id: 'json', name: 'JSON' },
  { id: 'yaml', name: 'YAML' },
  { id: 'xml', name: 'XML' },
  { id: 'markdown', name: 'Markdown' },
  { id: 'sql', name: 'SQL' },
  { id: 'shellscript', name: 'Shell/Bash' },
  { id: 'powershell', name: 'PowerShell' },
  { id: 'dockerfile', name: 'Dockerfile' },
  { id: 'graphql', name: 'GraphQL' },
  { id: 'vue', name: 'Vue' },
  { id: 'svelte', name: 'Svelte' },
  { id: 'jsx', name: 'JSX' },
  { id: 'tsx', name: 'TSX' },
  { id: 'dart', name: 'Dart' },
  { id: 'scala', name: 'Scala' },
  { id: 'r', name: 'R' },
  { id: 'matlab', name: 'MATLAB' },
  { id: 'perl', name: 'Perl' },
  { id: 'lua', name: 'Lua' },
  { id: 'haskell', name: 'Haskell' },
  { id: 'elixir', name: 'Elixir' },
  { id: 'clojure', name: 'Clojure' },
  { id: 'fsharp', name: 'F#' },
  { id: 'objective-c', name: 'Objective-C' },
  { id: 'assembly', name: 'Assembly' },
  { id: 'vb', name: 'Visual Basic' },
  { id: 'groovy', name: 'Groovy' },
  { id: 'julia', name: 'Julia' },
  { id: 'ocaml', name: 'OCaml' },
  { id: 'zig', name: 'Zig' },
  { id: 'nim', name: 'Nim' },
  { id: 'terraform', name: 'Terraform' },
  { id: 'toml', name: 'TOML' },
];

export const THEMES: Theme[] = [
  { id: 'andromeeda', name: 'Andromeeda', type: 'dark' },
  { id: 'aurora-x', name: 'Aurora X', type: 'dark' },
  { id: 'ayu-dark', name: 'Ayu Dark', type: 'dark' },
  { id: 'catppuccin-frappe', name: 'Catppuccin Frappé', type: 'dark' },
  { id: 'catppuccin-macchiato', name: 'Catppuccin Macchiato', type: 'dark' },
  { id: 'catppuccin-mocha', name: 'Catppuccin Mocha', type: 'dark' },
  { id: 'dark-plus', name: 'Dark+', type: 'dark' },
  { id: 'dracula', name: 'Dracula', type: 'dark' },
  { id: 'dracula-soft', name: 'Dracula Soft', type: 'dark' },
  { id: 'github-dark', name: 'GitHub Dark', type: 'dark' },
  { id: 'github-dark-default', name: 'GitHub Dark Default', type: 'dark' },
  { id: 'github-dark-dimmed', name: 'GitHub Dark Dimmed', type: 'dark' },
  { id: 'github-dark-high-contrast', name: 'GitHub Dark High Contrast', type: 'dark' },
  { id: 'houston', name: 'Houston', type: 'dark' },
  { id: 'laserwave', name: 'Laserwave', type: 'dark' },
  { id: 'material-theme', name: 'Material Theme', type: 'dark' },
  { id: 'material-theme-darker', name: 'Material Darker', type: 'dark' },
  { id: 'material-theme-ocean', name: 'Material Ocean', type: 'dark' },
  { id: 'material-theme-palenight', name: 'Material Palenight', type: 'dark' },
  { id: 'min-dark', name: 'Min Dark', type: 'dark' },
  { id: 'monokai', name: 'Monokai', type: 'dark' },
  { id: 'night-owl', name: 'Night Owl', type: 'dark' },
  { id: 'nord', name: 'Nord', type: 'dark' },
  { id: 'one-dark-pro', name: 'One Dark Pro', type: 'dark' },
  { id: 'poimandres', name: 'Poimandres', type: 'dark' },
  { id: 'red', name: 'Red', type: 'dark' },
  { id: 'rose-pine', name: 'Rosé Pine', type: 'dark' },
  { id: 'rose-pine-moon', name: 'Rosé Pine Moon', type: 'dark' },
  { id: 'slack-dark', name: 'Slack Dark', type: 'dark' },
  { id: 'solarized-dark', name: 'Solarized Dark', type: 'dark' },
  { id: 'synthwave-84', name: "Synthwave '84", type: 'dark' },
  { id: 'tokyo-night', name: 'Tokyo Night', type: 'dark' },
  { id: 'vesper', name: 'Vesper', type: 'dark' },
  { id: 'vitesse-black', name: 'Vitesse Black', type: 'dark' },
  { id: 'vitesse-dark', name: 'Vitesse Dark', type: 'dark' },
  { id: 'catppuccin-latte', name: 'Catppuccin Latte', type: 'light' },
  { id: 'github-light', name: 'GitHub Light', type: 'light' },
  { id: 'github-light-default', name: 'GitHub Light Default', type: 'light' },
  { id: 'github-light-high-contrast', name: 'GitHub Light High Contrast', type: 'light' },
  { id: 'light-plus', name: 'Light+', type: 'light' },
  { id: 'material-theme-lighter', name: 'Material Lighter', type: 'light' },
  { id: 'min-light', name: 'Min Light', type: 'light' },
  { id: 'one-light', name: 'One Light', type: 'light' },
  { id: 'rose-pine-dawn', name: 'Rosé Pine Dawn', type: 'light' },
  { id: 'slack-ochin', name: 'Slack Ochin', type: 'light' },
  { id: 'snazzy-light', name: 'Snazzy Light', type: 'light' },
  { id: 'solarized-light', name: 'Solarized Light', type: 'light' },
  { id: 'vitesse-light', name: 'Vitesse Light', type: 'light' },
];

export const DEFAULTS = {
  language: 'auto',
  theme: 'github-dark',
};
